-- MySQL Script generated by MySQL Workbench
-- Sat Feb 21 23:09:07 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Estado` (
  `idEstado` INT NOT NULL AUTO_INCREMENT,
  `estNombre` VARCHAR(50) NOT NULL,
  `estClaveEntidad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEstado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Municipio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Municipio` (
  `idMunicipio` INT NOT NULL AUTO_INCREMENT,
  `munNombre` VARCHAR(45) NOT NULL,
  `Estado_idEstado` INT NOT NULL,
  `munClaveIdentidad` INT NOT NULL,
  `munClave` INT NOT NULL,
  PRIMARY KEY (`idMunicipio`, `Estado_idEstado`),
  INDEX `fk_Municipio_Estado_idx` (`Estado_idEstado` ASC) VISIBLE,
  CONSTRAINT `fk_Municipio_Estado`
    FOREIGN KEY (`Estado_idEstado`)
    REFERENCES `mydb`.`Estado` (`idEstado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Colonia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Colonia` (
  `idColonia` INT NOT NULL AUTO_INCREMENT,
  `colCodigoPostal` INT NOT NULL,
  `colNombre` VARCHAR(45) NOT NULL,
  `Municipio_idMunicipio` INT NOT NULL,
  `Municipio_Estado_idEstado` INT NOT NULL,
  PRIMARY KEY (`idColonia`, `Municipio_idMunicipio`, `Municipio_Estado_idEstado`),
  INDEX `fk_Colonia_Municipio1_idx` (`Municipio_idMunicipio` ASC, `Municipio_Estado_idEstado` ASC) VISIBLE,
  CONSTRAINT `fk_Colonia_Municipio1`
    FOREIGN KEY (`Municipio_idMunicipio` , `Municipio_Estado_idEstado`)
    REFERENCES `mydb`.`Municipio` (`idMunicipio` , `Estado_idEstado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Direccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Direccion` (
  `idUsuDireccion` INT NOT NULL AUTO_INCREMENT,
  `UdirCalle` VARCHAR(45) NOT NULL,
  `UdirNumExterior` INT NULL,
  `UdirNumInterior` INT NULL,
  `UdirTieneNum` TINYINT NULL,
  `UdirReferencia` VARCHAR(500) NULL,
  `Colonia_idColonia` INT NOT NULL,
  `Colonia_Municipio_idMunicipio` INT NOT NULL,
  `Colonia_Municipio_Estado_idEstado` INT NOT NULL,
  PRIMARY KEY (`idUsuDireccion`, `Colonia_idColonia`, `Colonia_Municipio_idMunicipio`, `Colonia_Municipio_Estado_idEstado`),
  INDEX `fk_Direccion_Colonia1_idx` (`Colonia_idColonia` ASC, `Colonia_Municipio_idMunicipio` ASC, `Colonia_Municipio_Estado_idEstado` ASC) VISIBLE,
  CONSTRAINT `fk_Direccion_Colonia1`
    FOREIGN KEY (`Colonia_idColonia` , `Colonia_Municipio_idMunicipio` , `Colonia_Municipio_Estado_idEstado`)
    REFERENCES `mydb`.`Colonia` (`idColonia` , `Municipio_idMunicipio` , `Municipio_Estado_idEstado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Rol` (
  `idRol` INT NOT NULL AUTO_INCREMENT,
  `rolNombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idRol`),
  UNIQUE INDEX `idRol_UNIQUE` (`idRol` ASC) VISIBLE,
  UNIQUE INDEX `rolNombre_UNIQUE` (`rolNombre` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `usuNom` VARCHAR(50) NOT NULL,
  `usuPrimerApellido` VARCHAR(45) NOT NULL,
  `usuSegundoApellido` VARCHAR(45) NOT NULL,
  `usuRFC` VARCHAR(13) NOT NULL,
  `usuCURP` VARCHAR(18) NOT NULL,
  `usuFechaNacimiento` DATE NOT NULL,
  `usuSexo` CHAR(1) NOT NULL,
  `Direccion_idUsuDireccion` INT NOT NULL,
  `Direccion_Colonia_idColonia` INT NOT NULL,
  `Direccion_Colonia_Municipio_idMunicipio` INT NOT NULL,
  `Direccion_Colonia_Municipio_Estado_idEstado` INT NOT NULL,
  `usuVoluntarioEmpleado` TINYINT NOT NULL,
  `usuContrasenna` VARCHAR(45) NOT NULL,
  `usuEmail` VARCHAR(45) NOT NULL,
  `Rol_idRol` INT NOT NULL,
  `usuActivo` TINYINT NOT NULL,
  `usuFechaRegistro` DATETIME NOT NULL,
  `usuImagen` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`idUsuario`, `Direccion_idUsuDireccion`, `Direccion_Colonia_idColonia`, `Direccion_Colonia_Municipio_idMunicipio`, `Direccion_Colonia_Municipio_Estado_idEstado`, `Rol_idRol`),
  UNIQUE INDEX `idUsuario_UNIQUE` (`idUsuario` ASC) VISIBLE,
  UNIQUE INDEX `usuRFC_UNIQUE` (`usuRFC` ASC) VISIBLE,
  UNIQUE INDEX `usuCURP_UNIQUE` (`usuCURP` ASC) VISIBLE,
  INDEX `fk_Usuario_Direccion1_idx` (`Direccion_idUsuDireccion` ASC, `Direccion_Colonia_idColonia` ASC, `Direccion_Colonia_Municipio_idMunicipio` ASC, `Direccion_Colonia_Municipio_Estado_idEstado` ASC) VISIBLE,
  INDEX `fk_Usuario_Rol1_idx` (`Rol_idRol` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_Direccion1`
    FOREIGN KEY (`Direccion_idUsuDireccion` , `Direccion_Colonia_idColonia` , `Direccion_Colonia_Municipio_idMunicipio` , `Direccion_Colonia_Municipio_Estado_idEstado`)
    REFERENCES `mydb`.`Direccion` (`idUsuDireccion` , `Colonia_idColonia` , `Colonia_Municipio_idMunicipio` , `Colonia_Municipio_Estado_idEstado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_Rol1`
    FOREIGN KEY (`Rol_idRol`)
    REFERENCES `mydb`.`Rol` (`idRol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EquipoMultidisciplinario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EquipoMultidisciplinario` (
  `idEquipoMultidisciplinario` INT NOT NULL AUTO_INCREMENT,
  `equClave` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`idEquipoMultidisciplinario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario_has_EquipoMultidisciplinario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario_has_EquipoMultidisciplinario` (
  `Usuario_idUsuario` INT NOT NULL,
  `Usuario_Direccion_idUsuDireccion` INT NOT NULL,
  `Usuario_Direccion_Colonia_idColonia` INT NOT NULL,
  `Usuario_Direccion_Colonia_Municipio_idMunicipio` INT NOT NULL,
  `Usuario_Direccion_Colonia_Municipio_Estado_idEstado` INT NOT NULL,
  `Usuario_Rol_idRol` INT NOT NULL,
  `EquipoMultidisciplinario_idEquipoMultidisciplinario` INT NOT NULL,
  PRIMARY KEY (`Usuario_idUsuario`, `Usuario_Direccion_idUsuDireccion`, `Usuario_Direccion_Colonia_idColonia`, `Usuario_Direccion_Colonia_Municipio_idMunicipio`, `Usuario_Direccion_Colonia_Municipio_Estado_idEstado`, `Usuario_Rol_idRol`, `EquipoMultidisciplinario_idEquipoMultidisciplinario`),
  INDEX `fk_Usuario_has_EquipoMultidisciplinario_EquipoMultidiscipli_idx` (`EquipoMultidisciplinario_idEquipoMultidisciplinario` ASC) VISIBLE,
  INDEX `fk_Usuario_has_EquipoMultidisciplinario_Usuario1_idx` (`Usuario_idUsuario` ASC, `Usuario_Direccion_idUsuDireccion` ASC, `Usuario_Direccion_Colonia_idColonia` ASC, `Usuario_Direccion_Colonia_Municipio_idMunicipio` ASC, `Usuario_Direccion_Colonia_Municipio_Estado_idEstado` ASC, `Usuario_Rol_idRol` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_has_EquipoMultidisciplinario_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario` , `Usuario_Direccion_idUsuDireccion` , `Usuario_Direccion_Colonia_idColonia` , `Usuario_Direccion_Colonia_Municipio_idMunicipio` , `Usuario_Direccion_Colonia_Municipio_Estado_idEstado` , `Usuario_Rol_idRol`)
    REFERENCES `mydb`.`Usuario` (`idUsuario` , `Direccion_idUsuDireccion` , `Direccion_Colonia_idColonia` , `Direccion_Colonia_Municipio_idMunicipio` , `Direccion_Colonia_Municipio_Estado_idEstado` , `Rol_idRol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_has_EquipoMultidisciplinario_EquipoMultidisciplina1`
    FOREIGN KEY (`EquipoMultidisciplinario_idEquipoMultidisciplinario`)
    REFERENCES `mydb`.`EquipoMultidisciplinario` (`idEquipoMultidisciplinario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
